FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache openssl

COPY package*.json ./
COPY prisma ./prisma

RUN npm ci --ignore-scripts
RUN npx prisma generate --schema=./prisma/schema.prisma

COPY server ./server
COPY tsconfig*.json ./

EXPOSE 3001

CMD ["sh", "-c", "npx prisma migrate deploy && npx tsx server/index.ts"]
